version: "3.3"
services:
  api:
    container_name: tb-api
    image: tb/api:latest
    build:
      context: ./services/api/
      dockerfile: ../../docker/build/api/Dockerfile
    ports:
      - "8888:8888"
    restart: always
    tty: true
    privileged: true
    links:
      - db
    depends_on:
      - db
    # networks:
    #   - app_net
  db:
    container_name: tb-db
    image: tb/db:latest
    build: ./docker/build/db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/build/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/build/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./services/db/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tobi}
      POSTGRES_USER: ${POSTGRES_USER:-su}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
    restart: always
    # tty: true
    networks:
      - back-end
networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge